workflow:
  rules:
    # Exclude commits with a title containing "[no-ci]"
    - if: $CI_COMMIT_TITLE =~ /\[no-ci\]/
      when: never

    # Don't run for the source branch if there is an open merge request (to avoid duplicate builds)
    # https://docs.gitlab.com/ee/ci/yaml/workflow.html#switch-between-branch-pipelines-and-merge-request-pipelines
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never

    # Run for merge requests, or...
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

    # or run if the branch is the v3.x.x, v3.x.x-hotfix, master or develop branch
    - if: $CI_COMMIT_REF_NAME =~ /(\.x\.x|master|develop)/

    # or run if there is a tag
    - if: $CI_COMMIT_TAG != null

stages:
  - Unit Tests
  - Docker Dokos

unittests:
  image: "python:3.10-buster"

  stage: Unit Tests

  rules:
    # Skip if the commit message contains "[skip-tests]"
    - if: $CI_COMMIT_MESSAGE =~ /\[skip-tests\]/
      when: never
    - if: $CI_COMMIT_REF_NAME =~ /(\.x\.x|master|develop)/
      variables:
        BASE_BRANCH: "${CI_COMMIT_REF_NAME}"
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "v3.x.x-hotfix"
      variables:
        BASE_BRANCH: "v3.x.x-hotfix"
    - if: $CI_COMMIT_MESSAGE =~ /\[dodock-branch=(.*)\]/
    - if: $CI_COMMIT_TAG == null

  services:
    - name: mariadb:10.6
      command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--character-set-client-handshake=FALSE', '--innodb_read_only_compressed=OFF']
    - name: redis
      alias: redis_queue
    - name: redis
      alias: redis_cache
    - name: redis
      alias: redis_socketio

  variables:
    BASE_BRANCH: "develop"
    MYSQL_DATABASE: "test_dodock"
    MYSQL_ROOT_PASSWORD: "test_dodock"

  before_script:
    # Fetch base branch from commit message if it contains "[dodock-branch=<branch>]"
    - export BRANCH_FROM_COMMIT_MESSAGE=$(echo "$CI_COMMIT_MESSAGE" | sed -n 's/.*\[dodock-branch=\(.*\)\].*/\1/p')
    - if [ -n "$BRANCH_FROM_COMMIT_MESSAGE" ]; then export BASE_BRANCH="$BRANCH_FROM_COMMIT_MESSAGE"; fi

    - apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-suggests --no-install-recommends mariadb-client xfonts-75dpi xfonts-base
    - export LANG=C.UTF-8
    - export LC_ALL=C.UTF-8
    - export LANGUAGE=en_US.UTF-8
    - wget -q https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.buster_amd64.deb
    - dpkg -i wkhtmltox_0.12.6-1.buster_amd64.deb && rm wkhtmltox_0.12.6-1.buster_amd64.deb
    - rm -rf /var/lib/apt/lists/*
    - rm -rf /etc/apt/sources.list.d/*
    - curl -sL https://deb.nodesource.com/setup_16.x | bash
    - apt-get install -y nodejs
    - npm install --global yarn
    - export PATH=$PATH:/home/dokotest/.local/bin
    - adduser --disabled-password --gecos "" dokotest
    - usermod -aG sudo dokotest
    - echo 'dokotest ALL=(ALL)  NOPASSWD:ALL' >> /etc/sudoers
    - su -c "pip install dokos-cli" dokotest
    - su -c "cd /home/dokotest && bench init dokos-bench --no-backups --skip-redis-config-generation --skip-assets --frappe-branch $BASE_BRANCH" dokotest
    - su -c "cd /home/dokotest/dokos-bench && bench get-app https://gitlab.com/dokos/payments.git --branch develop" dokotest
    - su -c "cd /home/dokotest/dokos-bench && bench get-app /builds/dokos/dokos/" dokotest
    - su -c "cd /home/dokotest/dokos-bench && bench config set-common-config -c redis_queue redis://redis_queue:6379 -c redis_cache redis://redis_cache:6379 -c redis_socketio redis://redis_socketio:6379" dokotest
    - su -c "cp -r /home/dokotest/dokos-bench/apps/frappe/test_sites/test_site /home/dokotest/dokos-bench/sites/" dokotest
    - su -c "cd /home/dokotest/dokos-bench && sed -i 's/^watch:/# watch:/g' Procfile"
    - su -c "cd /home/dokotest/dokos-bench && sed -i 's/^schedule:/# schedule:/g' Procfile"
    - su -c "cd /home/dokotest/dokos-bench && sed -i 's/^socketio:/# socketio:/g' Procfile"
    - su -c "cd /home/dokotest/dokos-bench && sed -i 's/^redis_socketio:/# redis_socketio:/g' Procfile"
    - su -c "cd /home/dokotest/dokos-bench && cat Procfile"
    - su -c "cd /home/dokotest/dokos-bench && /home/dokotest/dokos-bench/env/bin/python -m pip install --quiet hypothesis==6.68.2 unittest-xml-reporting"
    - su -c "cd /home/dokotest/dokos-bench && bench start &> bench_start.log &" dokotest
    - su -c "cd /home/dokotest/dokos-bench && bench --site test_site reinstall --yes --mariadb-root-password test_dodock" dokotest
    - su -c "cd /home/dokotest/dokos-bench && bench --site test_site install-app payments" dokotest
    - su -c "cd /home/dokotest/dokos-bench && bench --site test_site install-app erpnext" dokotest
    - su -c "cd /home/dokotest/dokos-bench && bench build --app erpnext" dokotest

  script:
    - su -c "cd /home/dokotest/dokos-bench && bench --site test_site run-parallel-tests --app erpnext" dokotest

build_docker:
  stage: Docker Dokos
  rules:  # Run if the commit is tagged or if its message contains "[build-docker]"
    - if: $CI_COMMIT_TAG != null
    - if: $CI_COMMIT_MESSAGE =~ /\[build-docker\]/
  image: docker:git
  services:
    - docker:dind
  variables:
    DOKOS_BRANCH: "${CI_COMMIT_REF_NAME}"
    DODOCK_BRANCH: "v3.x.x-hotfix"
  script:
    # Set image tag
    - IMAGE_TAG=$CI_COMMIT_TAG
    - if [ -z "$IMAGE_TAG" ]; then
        IMAGE_TAG=$CI_COMMIT_SHORT_SHA;
      fi

    # Override image tag from commit message if it contains "[docker-tag=<branch>]"
    - TAG_FROM_COMMIT_MESSAGE=$(echo "$CI_COMMIT_MESSAGE" | sed -n 's/.*\[docker-tag=\(.*\)\].*/\1/p')
    - if [ -n "$TAG_FROM_COMMIT_MESSAGE" ]; then IMAGE_TAG="$TAG_FROM_COMMIT_MESSAGE"; fi

    # Set image name
    - IMAGE_NAME="$CI_REGISTRY_IMAGE:$IMAGE_TAG"

    # Set dodock branch
    - if echo "$CI_COMMIT_REF_NAME" | grep -Eq '(\.x\.x|main|master|develop)'; then
        DODOCK_BRANCH="$CI_COMMIT_REF_NAME";
      fi

    # Override dodock branch from commit message if it contains "[dodock-branch=<branch>]"
    - BRANCH_FROM_COMMIT_MESSAGE=$(echo "$CI_COMMIT_MESSAGE" | sed -n 's/.*\[dodock-branch=\(.*\)\].*/\1/p')
    - if [ -n "$BRANCH_FROM_COMMIT_MESSAGE" ]; then
        DODOCK_BRANCH="$BRANCH_FROM_COMMIT_MESSAGE";
      fi

    - echo "Building image $IMAGE_NAME"
    - git clone https://github.com/frappe/frappe_docker.git
    - cd frappe_docker
    - |-
      export APPS_JSON=$(cat <<-EOF
      [
        {
          "url": "https://gitlab.com/dokos/payments",
          "branch": "develop"
        },
        {
          "url": "https://gitlab.com/dokos/hrms",
          "branch": "develop"
        },
        {
          "url": "https://gitlab.com/dokos/dokos",
          "branch": "$DOKOS_BRANCH"
        }
      ]
      EOF
      )
    - echo ${APPS_JSON}
    - export APPS_JSON_BASE64=$(echo ${APPS_JSON} | base64 -w 0)
    - echo $APPS_JSON_BASE64
    - >
      docker build \
        --build-arg=FRAPPE_PATH=https://gitlab.com/dokos/dodock \
        --build-arg=FRAPPE_BRANCH=$DODOCK_BRANCH \
        --build-arg=PYTHON_VERSION=3.10.6 \
        --build-arg=NODE_VERSION=16.19.0 \
        --build-arg=APPS_JSON_BASE64="$APPS_JSON_BASE64" \
        --tag=$IMAGE_NAME \
        --file=images/custom/Containerfile .

    - echo "Logging in to registry $CI_REGISTRY"
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

    - echo "Pushing image $IMAGE_NAME"
    - docker push $IMAGE_NAME

    # Push latest tag if the commit is tagged
    - if [ -n "$CI_COMMIT_TAG" ]; then
        N="$CI_REGISTRY_IMAGE:latest"
        echo "Pushing image $N"; docker tag $IMAGE_NAME $N; docker push $N;
      fi

    # Push hotfix tag if the commit is on the hotfix branch
    - if [ "$CI_COMMIT_REF_NAME" = "v3.x.x-hotfix" ]; then
        N="$CI_REGISTRY_IMAGE:hotfix"
        echo "Pushing image $N"; docker tag $IMAGE_NAME $N; docker push $N;
      fi

    # Push develop tag if the commit is on the develop branch
    - if [ "$CI_COMMIT_REF_NAME" = "develop" ]; then
        N="$CI_REGISTRY_IMAGE:develop"
        echo "Pushing image $N"; docker tag $IMAGE_NAME $N; docker push $N;
      fi
